version: '3.3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: business-api-rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres